# RuboCop configuration for Sleep Tracker Rails

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

# Disable documentation requirement
Style/Documentation:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/users_controller.rb'
    - 'app/use_cases/*/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/*_controller.rb'
    - 'app/use_cases/*/*.rb'