# RuboCop configuration for Sleep Tracker Rails

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

# Disable documentation requirement
Style/Documentation:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/controllers/sleep_records_controller_spec.rb'